services:
#    yust_play_it.example:
#        class: Yust\PlayItBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    fileManager:
        class: Yust\PlayItBundle\Utils\fileManager
        arguments: ["@doctrine"]
    app.form.type.groups:
        class: Yust\PlayItBundle\Form\Type\DeviceType
        arguments: ["@doctrine.orm.entity_manager","@security.authorization_checker","@security.token_storage"]
        tags:
           - { name: form.type, alias: device }
